### PR TITLE
Remove . prefix from relative pathnames

### PR DESCRIPTION
**Pull request by Maroloccio**

### CODE REVIEW

**Comment by mustafaquraish** [comment]
On a second thought, I kind of like the `./` to explicitly specify the file(s) are in the current folder

**Comment by Maroloccio** [comment]
> On a second thought, I kind of like the `./` to explicitly specify the file(s) are in the current folder

I wonder where the files could be otherwise, though, if not in the current folder.

**Comment by mustafaquraish** [comment]
Doesn't hurt to be explicit though, does it? 😄

**Comment by Maroloccio** [comment]
> Doesn't hurt to be explicit though, does it? 😄

In Python, would you specify `None` in `dict.get("key", None)` in the same spirit? It's the default, but being explicit "doesn't hurt".

**Pull request closed without merging**
